### ISSUE TITLE
Hey, got some strict mode violation warning

### ISSUE THREAD

**Issue by david-serrano** [jonfinerty/Once#17]
```
D/StrictMode: StrictMode policy violation; ~duration=8 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=19 violation=2
                                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
                                                                       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:202)
                                                                       at android.app.SharedPreferencesImpl.getAll(SharedPreferencesImpl.java:214)
                                                                       at jonathanfinerty.once.PersistedMap.<init>(PersistedMap.java:17)
                                                                       at jonathanfinerty.once.Once.initialise(Once.java:34)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4603)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)`

`D/StrictMode: StrictMode policy violation; ~duration=4 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=19 violation=2
                                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
                                                                       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:202)
                                                                       at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:230)
                                                                       at jonathanfinerty.once.PersistedSet.<init>(PersistedSet.java:19)
                                                                       at jonathanfinerty.once.Once.initialise(Once.java:38)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4603)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5310)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by jonfinerty** [comment]
Thanks, I'll have a look into this. Might be able to load async, lazy load or something.
