### ISSUE TITLE
NumberFormatException: Invalid long

### ISSUE THREAD

**Issue by ChengKeven** [jonfinerty/Once#34]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.cyou.cma.clauncher.LauncherApplication: java.lang.NumberFormatException: Invalid long: "149744985210°"
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NumberFormatException: Invalid long: "149744985210°"
       at java.lang.Long.invalidLong(Long.java:124)
       at java.lang.Long.parse(Long.java:361)
       at java.lang.Long.parseLong(Long.java:352)
       at java.lang.Long.parseLong(Long.java:318)
       at jonathanfinerty.once.PersistedMap.stringToList(PersistedMap.java:1124)
       at jonathanfinerty.once.PersistedMap.get(PersistedMap.java:59)
       at jonathanfinerty.once.Once.beenDone(Once.java:166)
       at jonathanfinerty.once.Once.beenDone$4f70807c(Once.java:151)
       at com.cyou.cma.clauncher.LauncherApplication.onCreate(LauncherApplication.java:282)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4725)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jonfinerty** [comment]
Hi ChengKeven,

Thanks for using Once and raising an issue. Could you give a bit more detail on this Exception beyond the stacktrace? I don't know why you'd be getting a `°` character in your long, are you doing anything unusual with SharedPreferences or weird tag strings?

**Comment by ChengKeven** [comment]
Hello, jonfinerty:
      i cannot figure out why this crash produce.  i found it in fabric,  while this crash occurs 2000+ times only among 4 users.  the crash occurs when call " Once.beenDone(Once.THIS_APP_VERSION, "ON_NOTIFICATION") "

**Comment by ChengKeven** [comment]
only showed at one device,  not all device, ignore
